version: "3.8"
services:
  api:
    build: ./api
    container_name: next_productivity
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - ./app/node_modules
  nextproductivity:
    build: ./carpeta madre proyecto
    container_name: next_productivity
    ports:
      - "3000:3000"
    volumes:
      - ./next_productivity:/app
      - ./app/node_modules
    stdin_open: true
    tty: true
